import angular from 'angular';
import 'angular-sanitize';

// Import Material Design
import 'angular-animate';
import 'angular-aria';
import 'angular-material';

// Import app config files
import constants  from './config/app.constants';
import appConfig  from './config/app.config';
import appRun     from './config/app.run';
import 'angular-ui-router';
// Import templates file generated by Gulp
import './config/app.templates';
// Import app functionaity
import './components';
import './home';


// Create and bootstrap application
const requires = [
    'ngMaterial',
    'ngSanitize',
    'ui.router',
    'templates',
    'app.components',
    'app.home',
];

// Mount on window for testing
window.app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

angular.module('app').config(appConfig);

angular.module('app').run(appRun);

angular.bootstrap(document, ['app'], {
    strictDi: true
});
